### ISSUE TITLE
Invalid credentials (Wrong redirect_uri)

### ISSUE THREAD

**Issue by RPGer** [incubus/omniauth-odnoklassniki#10]
Добрый день.
Devise + omniauth-odnoklassniki
Возился с проблемой весь день. При авторизации идет переадресация на */users/sign_in* с ошибкой:
> Could not authenticate you from Odnoklassniki because "Invalid credentials". 

Дамп ответа показал, что на этапе получения *access_token* приходит следующий ответ:
> {"error_description":"Wrong redirect_uri","error":"invalid_request"}

Ошибка ставит в тупик, т.к. список допустимых *redirect_uri* в одноклассниках указан верно.
Решил проблему поправкой функции *callback_url* (/lib/omniauth/strategies/odniklassniki.rb):
```
def callback_url
	options.redirect_url || (full_host + script_name + callback_path)
end
```

**Comment by incubus** [comment]
Здравствуйте!

  Только что проверил на боевом сервере. Все работает. А у вас в итоге full_host + script_name + callback_path что возвращает? Можете еще сразу проверить ссылку в браузере https://connect.ok.ru/oauth/authorize?client_id=app_key&redirect_uri=_ваш redirect_uri_. Он верный?

**Comment by RPGer** [comment]
По адресу `https://connect.ok.ru/oauth/authorize?client_id=app_key&redirect_uri=_мой_redirect_uri_` ошибки о неправильном *uri* нет, пустой ответ (так и должно быть, насколько я понимаю). Ошибка появляется на этапе получения *access_token*.
*full_host + script_name + callback_path* возвращает мой *uri* в чистом виде, какой и должен быть. Исходно *callback_url* возвращает тот же *uri* но с *?code=...&state=...* на конце.
omniauth-odnoklassniki-0.0.5, omniauth-1.3.1, omniauth-oauth2-1.4.0

**Comment by alekseyg** [comment]
I had the same issue and @RPGer's solution worked for me. I'm not sure exactly why it works, but it does.

**Comment by zhukovRoman** [comment]
Получил ту же ошибку. Следует отметить, что проблема на localhostе через localtunel.me есть, на реальном сервере не проверял. 
Действительно метод @RPGer решает проблему, но может быть тогда кто-то подскажет, как мне это изменение сохранить в репозитории, чтобы при деплое на сервер не изменять гем в исходниках. 
Можно конечно форкнуть просто. 
@incubus вроде фикс минимальный, можно его внести в гем?

**Comment by alekseyg** [comment]
@zhukovRoman I put it in an initializer and monkey patched the gem via `class_eval`.

`/config/initializers/odnoklassniki.rb`
```Ruby
# Fix Odnoklassniki OAuth gem via
# https://github.com/incubus/omniauth-odnoklassniki/issues/10

OmniAuth::Strategies::Odnoklassniki.class_eval do
  def callback_url
    options.redirect_url || (full_host + script_name + callback_path)
  end
end
```

**Comment by askrynnikov** [comment]
@incubus cтоит обновить номер версии, т.к. bundler берет omniauth-odnoklassniki (0.0.5), у меня полдня ушло на поиск решения проблемы :(
